config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :books
  # Defines the root path route ("/")
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h1 class="title">Books I read this year</h1>
<div class="item-list">
	<% @books.each do |book|%>
		<div class="book-card">
			<h2><%= link_to book.title, book %></h2>
			<p><%= book.author %></p>
			<p><%= book.description %></p>
			<p><%= book.rating %></p>
		</div>
	<% end%>
</div>

app/views/books/new.html.erb
<h1>Add new book</h1>

<%= form_with model: @book do |form| %>
	<% if form.object.errors.any?%>
		<div>
			<% form.object.errors.full_messages.each do |message|%>
				<div> <%= message %> </div>
			<% end %>
		</div>
	<% end%>
	<div>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</div>
	<div>
		<%= form.label :author %>
		<%= form.text_field :author%>
	</div>
	<div>
		<%= form.label :rating%>
		<%= form.text_field :rating%>
	</div>
	<div>
		<%= form.label :description%>
		<%= form.text_area :description%>
	</div>
	<%= form.submit%>
<% end %>

app/views/books/show.html.erb
<div class="book-card">
	<h2><%= @book.title %></h2>
	<p><%= @book.author %></p>
	<p><%= @book.description %></p>
	<p><%= @book.rating %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <%= javascript_importmap_tags %>
  </head>

  <body>
		<div class="main">
			<nav class="navbar">
				<ul>
					<li><span class="material-symbols-outlined"> book </span></li>
					<li><%= link_to 'Home', books_path() %></li>
					<li><%= link_to 'Add new book', new_book_path() %></li>
				</ul>
			</nav>
			<%= yield %>
		</div>
  </body>
</html>